[log]
log_name = "simbot.log"
stdout_level = "INFO"
file_level = "INFO"

[user]
# 登录的用户名密码
email = ""
password = ""

[notice.mail]
# 邮箱通知
host = "smtp.qq.com"
port = 465
username = ""
password = ""
[notice.bark]
# bark通知
bark_key = ""

[market]
# 交易行监控id列表
# e.g: item_list = [{ id = 32, quality = 0, price = 360 }, { id = 100, quality = 0, price = 300 }]
item_list = []