version: "3"
services:
  simbot:
    container_name: simbot
    image: ghcr.io/potatoii/simbot:main
    working_dir: /simbot
    restart: always
    volumes:
      - ./config.json:/simbot/config.json
      - ./logs:/simbot/logs
    command: "python main.py"
