on:
  push:
    branches:
    - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Env
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
          
      - name: PyInstaller Linux
        run: pyinstaller main.spec

      - name: Automatic Releases
        uses: google-github-actions/release-please-action@v4
        with:
          token: ${{ secrets.RELEASE_TOKEN }}
          release-type: python
          automatic_release_tag: "latest"
          title: "SimBot"
          path: ./dist/SimBot
