on:
  push:
    branches:
    - main
jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: PyInstaller Linux
        uses: JackMcKew/pyinstaller-action-linux@main
        with:
          path: .

      - name: Automatic Releases
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secret.RELEASE_TOEKN }}
          automatic_release_tag: "latest"
          title: "SimBot"
          files: ./dist/SimBot
